# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57e137b7c019c70a176fb50e2f93e608211ef154821ccfef3aa83064177c99834ab2c2c8df562412ea5a4739c7f06bd3e0e29b1b81dfdd957bd4f58dcdfb2278

test:
  secret_key_base: 151347842c9e6384308afb3eaf372f653cb6adf337ec56a72907d9e810a97cd233326688246409ed8e5969a06dc9958bc8a481f4d29bdef37180b690f0ec75ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
